repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0  # Use the latest stable version
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.2
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
